version: "3.9"
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: finagent
      POSTGRES_PASSWORD: finagent
      POSTGRES_DB: finagent
    ports: ["5432:5432"]
    volumes: ["pgdata:/var/lib/postgresql/data"]
  redis:
    image: redis:7-alpine
    ports: ["6379:6379"]
volumes:
  pgdata:
